"""Write the Shields-Bitz benchmark runs into the Results archive in FILLET v1.1 format, labelled as runs made by this analysis rather than as an author submission.

Shields-Bitz is a listed FILLET participant that has filed no deliverables, so
nothing under `Results/` represents it and the consortium's plotting scripts
cannot include it.  This step writes the three benchmark runs produced by
`dataRunShieldsBitzBenchmarks.py` into the directory layout
`Results/README.md` prescribes, so that the existing analysis scripts can read
it like any other code.

The provenance is stated in every file it writes, in the header, and it is the
reason this script exists as its own step rather than as a side effect of the
run: these numbers were generated here, from the public source, and were NOT
supplied by the model's authors.  A reader who finds `Results/shields_bitz/`
in six months must be able to tell that from the file alone, without knowing
this report exists.  Two protocol columns also cannot be filled honestly and
say so in the header rather than silently carrying a plausible number:

  XCO2   The model has no CO2 term at all -- its longwave is A + B T with
         both constants fixed -- so the protocol abundance is recorded as the
         nominal 280 ppm with a header line stating that it has no effect.
  Diff   The diffusion coefficient is not a constant but a Hadley-cell
         profile, D(x) = D_mag [1 + 9 exp(-(x / sin 25deg)^6)].  The base
         D_mag is written and the profile is stated in the header.
"""

import argparse
import json
import os

import numpy as np

ICE_THRESHOLD_K = 263.15
OBLIQUITY = {"ben1": 23.5, "ben2": 23.5, "ben3": 60.0}
GEOGRAPHY = {"ben1": "present-day Earth land fraction",
             "ben2": "uniform 25% land / 75% ocean",
             "ben3": "uniform 25% land / 75% ocean"}


def fdEdgeCrossing(aLat, aT, fThresholdK, bNorth):
    """Interpolated latitude at which the profile crosses the ice threshold."""
    aMask = aLat >= 0.0 if bNorth else aLat <= 0.0
    aL, aTT = aLat[aMask], aT[aMask]
    if bNorth:
        iOrder = np.argsort(aL)
    else:
        iOrder = np.argsort(-aL)
    aL, aTT = aL[iOrder], aTT[iOrder]
    aCross = np.nonzero((aTT[:-1] - fThresholdK) * (aTT[1:] - fThresholdK) < 0)[0]
    if not len(aCross):
        return None
    i = int(aCross[-1])
    fFrac = (fThresholdK - aTT[i]) / (aTT[i + 1] - aTT[i])
    return float(aL[i] + fFrac * (aL[i + 1] - aL[i]))


def flistIceEdges(aLat, aT, fThresholdK=ICE_THRESHOLD_K):
    """The v1.1 four-value block: N outer, N inner, S inner, S outer.

    The conventions are the ones `Results/hextor/ben1/global_output.dat`
    documents: ice-free is (90, 90, -90, -90); a snowball is (90, 0, 0, -90);
    polar caps put the interior edge at the crossing latitude.
    """
    aNorth = aT[aLat >= 0.0]
    aSouth = aT[aLat <= 0.0]
    bNorthIceFree = bool(np.all(aNorth > fThresholdK))
    bSouthIceFree = bool(np.all(aSouth > fThresholdK))
    bNorthAllIce = bool(np.all(aNorth <= fThresholdK))
    bSouthAllIce = bool(np.all(aSouth <= fThresholdK))

    if bNorthIceFree and bSouthIceFree:
        return [90.0, 90.0, -90.0, -90.0]
    if bNorthAllIce and bSouthAllIce:
        return [90.0, 0.0, 0.0, -90.0]
    fN = fdEdgeCrossing(aLat, aT, fThresholdK, True)
    fS = fdEdgeCrossing(aLat, aT, fThresholdK, False)
    return [90.0, 90.0 if fN is None else fN,
            -90.0 if fS is None else fS, -90.0]


def flistLatHeader(sBench, dictB, sCommit, sDate):
    return [
        "# Shields-Bitz FILLET benchmark, GENERATED BY ANALYSIS, NOT AN AUTHOR SUBMISSION.",
        "# Produced by fillet/runShieldsBitz/dataRunShieldsBitzBenchmarks.py on %s" % sDate,
        "# from the public source at github.com/astrovidee/EBM, commit %s," % sCommit,
        "# run unmodified at the package defaults for %.0f orbits on %d boxes."
        % (dictB["dictConfig"]["runlength"], dictB["iNumLatitudes"]),
        "# The Shields-Bitz authors have not filed a FILLET submission; if they do,",
        "# it supersedes this file.",
        "#",
        "# Name of benchmark/experiment: Benchmark %s" % sBench[-1],
        "# Code: shields_bitz",
        "# Case number: 0",
        "# Instellation (S_earth): 1",
        "# XCO2 (ppm): 280   <- nominal only: the model has no CO2 term",
        "# Obliquity (degrees): %.1f" % OBLIQUITY[sBench],
        "# Geography: %s" % GEOGRAPHY[sBench],
        "# Surface albedo IS the planetary albedo: the model has no shortwave",
        "# atmosphere, so the Asurf and ATOA columns are necessarily equal.",
        "# Albedos are broadband values weighted for a G dwarf, not the",
        "# protocol's prescribed 0.30 / 0.20 / 0.60.",
        "",
        "# Columns of data (annually averaged for last orbit)",
        "# Lat = latitude (degrees)",
        "# Tsurf = annually averaged surface temperature (K)",
        "# Asurf = annually averaged surface albedo",
        "# ATOA = annually averaged top-of-atmosphere/total/planetary albedo",
        "# OLR = annually averaged outgoing longwave radiation (W m^-2)",
        "",
        "# Lat Tsurf Asurf ATOA OLR",
    ]


def flistGlobalHeader(sBench, dictB, sCommit, sDate):
    return [
        "# Shields-Bitz FILLET benchmark, GENERATED BY ANALYSIS, NOT AN AUTHOR SUBMISSION.",
        "# Produced by fillet/runShieldsBitz/dataRunShieldsBitzBenchmarks.py on %s" % sDate,
        "# from the public source at github.com/astrovidee/EBM, commit %s." % sCommit,
        "# The Shields-Bitz authors have not filed a FILLET submission; if they do,",
        "# it supersedes this file.",
        "#",
        "# Name of benchmark/experiment: Benchmark %s" % sBench[-1],
        "# Describe how ice line latitude is determined: the latitude at which the",
        "# annually-averaged surface temperature crosses 263.15 K, interpolated",
        "# between box centres on the model's own sin(latitude) grid.  NOTE: this",
        "# is NOT the quantity the package's own mean_iceline() returns, which is",
        "# the seasonal mean of the daily ocean freezing latitude and is evaluated",
        "# on a uniform-latitude axis the model does not use.",
        "# XCO2 is nominal: the model's longwave is A + B T with no CO2 term.",
        "# Diff is the base coefficient D_mag; the model uses a Hadley-cell profile",
        "# D(x) = D_mag [1 + 9 exp(-(x/sin 25deg)^6)], not a constant.",
        "",
        "# Columns of data",
        "# Case = case number (0 -> total number of cases in experiment)",
        "# Inst = instellation (S_earth; i.e., relative to Earth's 1361 W m^-2)",
        "# Obl = obliquity (degrees)",
        "# XCO2 = mixing ratio (volume) of CO2 (ppm)",
        "# Tglob = global, annual mean surface temperature (K)",
        "# IceLineNMax = latitude of northern edge of ice in northern hemisphere (deg)",
        "# IceLineNMin = latitude of southern edge of ice in northern hemisphere (deg)",
        "# IceLineSMax = latitude of northern edge of ice in southern hemisphere (deg)",
        "# IceLineSMin = latitude of southern edge of ice in southern hemisphere (deg)",
        "# Diff = diffusion coefficient (base value; see note above)",
        "# OLRglob = global, annual mean outgoing longwave radiation (W m^-2)",
        "",
        "# Case Inst Obl XCO2 Tglob IceLineNMax IceLineNMin IceLineSMax IceLineSMin Diff OLRglob",
    ]


def fvWriteBenchmark(sRoot, dictB, sCommit, sDate):
    """One benchmark directory: global_output.dat plus case_0/lat_output.dat."""
    sBench = dictB["sBenchmark"]
    aLat = np.array(dictB["aLat"], dtype=float)
    aT = np.array(dictB["aTsurf"], dtype=float)
    aAlb = np.array(dictB["aAsurf"], dtype=float)
    aOLR = np.array(dictB["aOLR"], dtype=float)

    sCaseDir = os.path.join(sRoot, sBench, "case_0")
    os.makedirs(sCaseDir, exist_ok=True)
    with open(os.path.join(sCaseDir, "lat_output.dat"), "w") as oFile:
        oFile.write("\n".join(flistLatHeader(sBench, dictB, sCommit, sDate)) + "\n")
        for fLat, fT, fA, fO in zip(aLat, aT, aAlb, aOLR):
            oFile.write("%.4f %.3f %.4f %.4f %.3f\n" % (fLat, fT, fA, fA, fO))

    listEdges = flistIceEdges(aLat, aT)
    fDmag = float(dictB["dictConfig"]["Dmag"])
    with open(os.path.join(sRoot, sBench, "global_output.dat"), "w") as oFile:
        oFile.write("\n".join(flistGlobalHeader(sBench, dictB, sCommit, sDate)) + "\n")
        oFile.write("0 1.00 %.1f %.1f %.3f %.1f %.1f %.1f %.1f %.2f %.3f\n"
                    % (OBLIQUITY[sBench], 280.0, dictB["fTglobK"],
                       listEdges[0], listEdges[1], listEdges[2], listEdges[3],
                       fDmag, dictB["fOLRGlobal"]))
    return {"sBenchmark": sBench, "listIceEdges": listEdges,
            "fTglobK": dictB["fTglobK"], "iNumLatitudes": dictB["iNumLatitudes"]}


def main():
    oParser = argparse.ArgumentParser(description=__doc__)
    oParser.add_argument("--benchmarks-json", required=True)
    oParser.add_argument("--results-dir", required=True,
                         help="the Results directory to write shields_bitz into")
    oParser.add_argument("--source-commit", default="815caef")
    oParser.add_argument("--date", default="22 September 2026")
    oParser.add_argument("--out", required=True)
    oArgs = oParser.parse_args()

    dictRuns = json.load(open(oArgs.benchmarks_json))
    sRoot = os.path.join(oArgs.results_dir, "shields_bitz")
    listWritten = [fvWriteBenchmark(sRoot, d, oArgs.source_commit, oArgs.date)
                   for d in dictRuns["listBenchmarks"]]

    json.dump({"sDirectory": sRoot, "iBenchmarks": len(listWritten),
               "sSourceCommit": oArgs.source_commit,
               "bAuthorSubmission": False,
               "listBenchmarks": listWritten},
              open(oArgs.out, "w"), indent=1)

    print("wrote %d benchmark directories under %s" % (len(listWritten), sRoot))
    print("%-6s %6s %9s   %s" % ("bench", "nlat", "Tglob", "ice edges (NMax NMin SMax SMin)"))
    for d in listWritten:
        print("%-6s %6d %9.3f   %s"
              % (d["sBenchmark"], d["iNumLatitudes"], d["fTglobK"],
                 " ".join("%.1f" % f for f in d["listIceEdges"])))
    print("\nheaders state these are generated by this analysis, not filed by the authors")


if __name__ == "__main__":
    main()
